baseurl = "/"

[params]
  env = "production"
  months = [ "null", "januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december" ]

# datocms:start
title = "Maand van de Filosofie Deventer"
languageCode = "nl"
# datocms:end