module.exports = (dato, root) => {
  root.createDataFile('site.yaml', 'yaml', dato.site.toMap());

  root.directory('data/', dir => {
    dato.singleInstanceItemTypes.forEach(itemType => {
      const item = dato.itemsOfType(itemType)[0];
      if (item) {
        dir.createDataFile(`${itemType.apiKey}.yaml`, 'yaml', item.toMap());
      }
    });
  });

  dato.collectionItemTypes.forEach(itemType => {
    root.directory(`content/_${itemType.apiKey}/`, dir => {
      dato.itemsOfType(itemType).forEach(item => {
        dir.createPost(`${item.autogeneratedSlug()}.md`, 'yaml', { frontmatter: item.toMap() });
      });
    });
  });
};