id: '1657'
name: Maand van de Filosofie Deventer - development
locales:
  - en
themeHue: 190
domain: null
internalDomain: maand-van-de-filosofie-deventer-development.admin.datocms.com
noIndex: false
globalSeo:
  siteName: Maand van de Filosofie Deventer
  titleSuffix: ''
  facebookPageUrl: 'https://www.facebook.com/maandvandefilosofie'
  twitterAccount: null
  fallbackSeo:
    title: Maand van de Filosofie Deventer
    description: >-
      Het doel van Deventer-Filosofiemaand April 2017 is de kracht, het nut en
      het plezier van filosofie en samen filosoferen onder de aandacht brengen.
    image:
      format: png
      size: 18062
      width: 340
      height: 340
      title: null
      alt: null
      url: >-
        https://dato-images.imgix.net/604/1479918022-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth
favicon: null
faviconMetaTags:
  - tagName: meta
    attributes:
      name: application-name
      content: Maand van de Filosofie Deventer - development