id: '970'
name: Maand van de Filosofie Deventer
locales:
  - nl
themeHue: 4
domain: null
internalDomain: maand-van-de-filosofie-deventer.admin.datocms.com
noIndex: false
globalSeo:
  siteName: Maand van de Filosofie Deventer
  titleSuffix: ''
  facebookPageUrl: 'https://www.facebook.com/maandvandefilosofie'
  twitterAccount: null
  fallbackSeo:
    title: Maand van de Filosofie Deventer
    description: >-
      Het doel van Deventer-Filosofiemaand April 2017 is de kracht, het nut en
      het plezier van filosofie en samen filosoferen onder de aandacht brengen.
    image:
      format: png
      size: 18062
      width: 340
      height: 340
      title: null
      alt: null
      url: >-
        https://dato-images.imgix.net/604/1479918022-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth
favicon:
  format: png
  size: 18062
  width: 340
  height: 340
  title: null
  alt: null
  url: >-
    https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth
faviconMetaTags:
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 57x57
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=57&w=57
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 60x60
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=60&w=60
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 72x72
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=72&w=72
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 76x76
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=76&w=76
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 114x114
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=114&w=114
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 120x120
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=120&w=120
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 144x144
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=144&w=144
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 152x152
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=152&w=152
  - tagName: link
    attributes:
      rel: apple-touch-icon
      sizes: 180x180
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=180&w=180
  - tagName: meta
    attributes:
      name: msapplication-square70x70
      content: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=70&w=70
  - tagName: meta
    attributes:
      name: msapplication-square150x150
      content: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=150&w=150
  - tagName: meta
    attributes:
      name: msapplication-square310x310
      content: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=310&w=310
  - tagName: meta
    attributes:
      name: msapplication-square310x150
      content: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=150&w=310
  - tagName: link
    attributes:
      rel: icon
      sizes: 16x16
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=16&w=16
      type: image/png
  - tagName: link
    attributes:
      rel: icon
      sizes: 32x32
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=32&w=32
      type: image/png
  - tagName: link
    attributes:
      rel: icon
      sizes: 96x96
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=96&w=96
      type: image/png
  - tagName: link
    attributes:
      rel: icon
      sizes: 192x192
      href: >-
        https://dato-images.imgix.net/604/1479917977-Screenshot2016-11-2317.18.52.png?auto=format&ch=DPR%2CWidth&h=192&w=192
      type: image/png
  - tagName: meta
    attributes:
      name: application-name
      content: Maand van de Filosofie Deventer